### ISSUE TITLE
Movement in horizontal wind tube

### ISSUE THREAD

**Issue by DorianHawkmoon** [MaturuturuStudios/Drop#2]
In horizontal wind tube, I'm able to move along the tube.

Desired behaviour: being able to move in vertical axis but not in horizontal axis (exactly the opposite behaviour in vertical wind tubes)

**Comment by IgnacioAstorga** [comment]
The problem is simple if the wind tube is horizontal, but what if the tube is rotated, let's say, 45 degrees? In which direction would you like to move? Up and down? Left and right? Both? The way it works now, the wind tube will work wrong if the movement direction is not perpendicular to the tube. Let's see if we can find a solution.

**Comment by DorianHawkmoon** [comment]
Maybe a simple way to solve this is allow the character to move in both direction but its velocity is modified by the vector of the wind. Not perfect but can work.

Example Vertical wind: 
- Vector x=0 y=1
- Get the inversed vector x=1,y=0
- Multiply by the input velocity means that in horizontal axis can move, but in vertical axis not.

Example horizontal wind
- Vector x=1 y=0
- Inversed x=0 y=1
- Multiplied, can move vertical but not horizontal

Example Rotated by 45º
- Vector x=0.5 y=0.5
- Inversed 0=0.5 y=0.5
- Multiplied, can move both direction but without total freedom

**Comment by IgnacioAstorga** [comment]
The problem is that without receiving input in one axis (or if the input is nullified), it will try to stop on that axis as it would do normally. This means that the velocity applied by the wind tube will also be decreased.
There is a parameter wich decides in which axis the character moves, that allows movement in vertical, horizontal or both. If horizontal is selected, the character won't stop on the vertical axis. The same happens when vertical is selected. This allows vertical and horizontal wind tubes, but not rotated ones.
So the question actually is how to move the character while on a, let's say, 45º wind tube.

**Comment by IgnacioAstorga** [comment]
I have reworked the wind tubes. Now the player will apply it's input on a different way while staying on a wind tube. This seems to fix some problems, including this one. I've also made some other improvements, check it out and close the issue if it's correct.

**Comment by DorianHawkmoon** [comment]
Seems to work correctly.
